title: Graph & Geometry Algorithms
description: A collection of algorithms in Graph Theory and Computational Geometry.
# theme: minima
markdown: kramdown
baseurl: ""
url: "https://jorgev92.github.io"
